# Copyright (C)2026 mcxedit
# Licensed under GPL-2.0-only. For further information,
# view `git log`, and the COPYING and CONTRIBUTORS files
# at www.github.com/thepigeongenerator/mcxedit.
SHELL = /bin/sh
.SUFFIXES:

VERSION = 0.0
NAME    = mcxedit

# Include a .config.mk, if it exists.
# Allowing users to write persistent configurations
-include .config.mk

GZ     ?= gzip
SPARSE ?= sparse
TAR    ?= tar
XXD    ?= xxd

SRC := $(shell find src/ -name '*.c' -print)
OBJ := $(addsuffix .o,$(SRC))
DEP := $(addsuffix .d,$(SRC))

CFLAGS   := -O2 $(CFLAGS) -g -std=gnu17\
	    -Wall -Wextra -Wpedantic -Wno-pointer-arith -Wvla
CPPFLAGS := -DNDEBUG -U_GNU_SOURCE $(CPPFLAGS)
LDFLAGS  := -flto $(LDFLAGS)
LDLIBS   := $(LDLIBS) -lm -larchive

# Set Q to @ to silence commands being printed, unless --no-silent has been set
ifeq (0, $(words $(findstring --no-silent,$(MAKEFLAGS))))
msg=@printf ' %-8s %s\n' "$(1)" "$(2)"
Q=@
else
msg=
Q=
endif

# detect if we're compiling on Windows, meaning
# a lot of things considered "standard" are unavailable.
ifeq ($(OS),Windows_NT)
include Windows_NT.mk
endif

# Default target; compiles everything.
all: $(NAME)

# Install a binary on a POSIX-compliant system.
install: $(NAME)
	install -m0755 $(NAME) $(DESTDIR)/bin/$(NAME)

uninstall:
	$(RM) $(DESTDIR)/bin/$(NAME)

check:
	$(Q)$(SPARSE) $(CPPFLAGS) $(CFLAGS) $(SRC)

clean:
	$(Q)$(RM) $(OBJ) $(DEP)

CONTRIBUTORS:
	$(Q)printf "# This file is generated by \`make $@\`, if editing manually, keep it sorted.\n" >CONTRIBUTORS~
	$(Q)printf "# List of all contributors of the project:\n" >>CONTRIBUTORS~
	$(Q)git log --format='%aN <%aE>%n%cN <%cE>' | sort -u >>CONTRIBUTORS~
	$(Q)mv CONTRIBUTORS~ CONTRIBUTORS
.PHONY: $(PHONY) all install uninstall dist distclean clean check CONTRIBUTORS

# Links together the object files into the final binary.
$(NAME): $(OBJ)
	$(call msg,LD,$@)
	$(Q)$(CC) $(LDFLAGS) $(LDLIBS) -o $@ $^

# Compiles C sources into object files
%.c.o: %.c
	$(call msg,CC,$@)
	$(Q)$(CC) -c $(CPPFLAGS) $(CFLAGS) -o $@ $<

%.gz: %
	$(call msg,GZ,$@)
	$(Q)$(GZ) -k $<

# Generate and include dependencies,
# ignoring any errors that may occur when doing so.
%.c.d: %.c; $(Q)$(CC) -MM $(CPPFLAGS) -MF $@ $<
ifeq (0, $(words $(findstring $(MAKECMDGOALS), clean)))
-include $(DEP)
endif

.PHONY: $(PHONY)
