# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: ©2026 Quinn Zieltjens <zieltjens@pigeonware.org>
SHELL = /bin/sh
.SUFFIXES:
.SECONDARY:

MAKEFLAGS += --no-print-directory

include Common.mk

# TODO: move this into a separate Makefile as well
MANSRC      := $(wildcard man/*/*.rst)
MANPAGES    := $(patsubst %.rst,%.gz,${MANSRC})

PHONY = all manpages

ifneq (${OS},Windows_NT)
all: libmcx.so libmcx.a mcxedit mcxedit.static
libmcx.a:               ; ${Q}${MAKE} -C src/libmcx  $@
libmcx.so:              ; ${Q}${MAKE} -C src/libmcx  $@
mcxedit: libmcx.so      ; ${Q}${MAKE} -C src/mcxedit $@
mcxedit.static: libmcx.a; ${Q}${MAKE} -C src/mcxedit $@

installdirs: | \
	${DESTDIR}${bindir}/ ${DESTDIR}${mandir}/ ${DESTDIR}${libdir}/\
	$(addprefix ${DESTDIR}${mandir}/,$(sort $(dir $(MANPAGES:man/%=%))))
install: all manpages | installdirs
	${Q}install -m0755 mcxedit   ${DESTDIR}${bindir}
	${Q}install -m0755 libmcx.so ${DESTDIR}${libdir}
	${Q}install -m0755 libmcx.a  ${DESTDIR}${libdir}
	${Q}for man in $(MANPAGES:man/%=%); do\
		install -m0644 "man/$$man" ${DESTDIR}${mandir}/"$$man";\
	done
uninstall:
	${Q}${RM} ${DESTDIR}${bindir}/mcxedit
	${Q}${RM} ${DESTDIR}${libdir}/libmcx.so
	${Q}${RM} ${DESTDIR}${libdir}/libmcx.a
	${Q}${RM} $(MANPAGES:man/%=${DESTDIR}${mandir}/%)
else
$(warning Detected  Windows_NT kernel, please refer to the documentation if you encounter issues.)
all: libmcx.dll libmcx.a mcxedit.exe
libmcx.a:            ; ${Q}${MAKE} -C src/libmcx  $@
libmcx.dll:          ; ${Q}${MAKE} -C src/libmcx  $@
mcxedit.exe: libmcx.a; ${Q}${MAKE} -C src/mcxedit $@

# BUG: I am purposefully neglecting this at the moment.
# TODO: Figure out what the fuck they do with files.
endif

manpages: ${MANPAGES}

# CLEANING
clean:
	${Q}${MAKE} -C src/libmcx  clean
	${Q}${MAKE} -C src/mcxedit clean
	${Q}${RM} ${MANPAGES}
PHONY += clean

# SEMANTIC CHECKING
check:
	${Q}${MAKE} -C src/libmcx  check
	${Q}${MAKE} -C src/mcxedit check
PHONY += check

# GENERATING TRACKED FILES
CONTRIBUTORS:
	${Q}printf "# Generated by \`make $@\`, if editing manually, keep it sorted.\n" >CONTRIBUTORS~
	${Q}printf "# List of all contributors of the project:\n" >>CONTRIBUTORS~
	${Q}git log --format='%aN <%aE>%n%cN <%cE>' | sort -u >>CONTRIBUTORS~
	${Q}mv CONTRIBUTORS~ CONTRIBUTORS
PHONY += CONTRIBUTORS

# MANPAGE CREATION
man/%: man/%.rst
	$(call msg,RST2MAN,$@)
	${Q}sed 's/@@VERSION@@/'${VERONLY}'/g;'\
	's/@@DATE@@/'$(shell date +%Y-%m-%d)'/g' $< | rst2man >$@
# Generate and include dependencies,
# ignoring any errors that may occur when doing so.
%.c.d: %.c; ${Q}${CC} -MM ${CPPFLAGS} -MF $@ $<
ifeq (0, $(words $(findstring ${MAKECMDGOALS}, clean)))
-include ${DEP}
endif

# Apply rules added to PHONY as phony rules.
# They are not checked against files.
.PHONY: ${PHONY}
