# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: ©2026 Quinn Zieltjens <zieltjens@pigeonware.org>

libmcx-cflags = -fPIC
libmcx-obj = err.o mcx.o nbt.o
-include $(libmcx-obj:%.o=%.d)
